#Eduardo Airton

#Site de Referência para as artes: http://ascii.co.uk/art/pokemon
class Artes:
    def pokemon(self):
        print("                                                                                                              ")
        print("                                                                          , \                                ")
        print("                                            _.----.        ____         ,'  _\   ___    ___     ____       \n")
        print("                                        _,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`. \n")
        print("                                        \      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |\n")
        print("                                         \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |\n")
        print("                                           \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |\n")
        print("                                            \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |\n")
        print("                                             \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |\n")
        print("                                              \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |\n")
        print("                                               \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |\n")
        print("                                                \_.-'       |__|    `-._ |              '-.|     '-.| |   |\n")
        print("                                                                        `'                            '-._|\n")
    def pokemon2(self):# Eevee
        print("        ;-.               ,\n")
        print("        \ '.           .'/\n")
        print("         \  \ .---. .-' /\n")
        print("          '. '     `\_.'\n")
        print("            |(),()  |     ,\n")
        print("            (  __   /   .' \n")
        print("           .''.___.'--,/\_,|\n")
        print("          {  /     \   }   |\n")
        print("           '.\     /_.'    /\n")
        print("            |'-.-',  `; _.'\n")
        print("            |  |  |   |`\n")
        print("            `\"\"`\"\"`\"\"\"`  \n")
    def pokemon3(self):# Meowth
        print("              .-. \_/ .-.\n")
        print("               \.-\/=\/.-/\n")
        print("            '-./___|=|___\.-'\n")
        print("           .--| \|/`\"`\/ |--.\n")
        print("          (((_)\  .---.  /(_)))\n")
        print("           `\ \_`-.   .-'_/ /`_\n")
        print("             '.__       __.'(_))\n")
        print("                 /     \     //\n")
        print("                |       |__.'/\n")
        print("                \       /--'`\n")
        print("            .--,-' .--. '----.\n")
        print("           '----`--'  '--`----'\n")

    def pokemon4(self):#    Kakuna
        print("         _.---._\n")
        print("       .'       '.\n")
        print("      /           \\n")
        print("     / /'-.   .-'\ \\n")
        print("     '.`\"\"\"` `\"\"\"`.'\n")
        print("      /'-._   _.-'\\n")
        print("     /_.--\`-`/--._\\n")
        print("     ;    |'-'|    ;\n")
        print("     |  .'/ | \'.  |\n")
        print("     |  | \ | / |  |\n")
        print("      \  \/\|/\/  /\n")
        print("       \_/  _  \_/\n")
        print("        |-'` `'-|\n")
        print("        |.-\"\"\"-.|\n")
        print("        \ .---. /\n")
        print("         '._ _.'\n")
        print("            `\n")

    def pokemon5(self):# Pikachu
        print("               ,     ,_\n")
        print("       |`\    `;;,            ,;;'\n")
        print("       |  `\    \ '.        .'.'\n")
        print("       |    `\   \  '-\"\"\"\"-' /\n")
        print("       `.     `\ /          |`\n")
        print("         `>    /;   _     _ \ \n")
        print("          /   / |       .    ;\n")
        print("         <  (`\";\ ()   ~~~  (/_\n")
        print("          ';;\  `,     __ _.-'` )\n")
        print("            >;\          `   _.'\n")
        print("            `;;\          \-'\n")
        print("              ;/           \ _\n")
        print("              |   ,"".     .` \\n")
        print("              |      _|   '   /\n")
        print("               ;    /\")     .;-,\n")
        print("                \    /  __   .-'\n")
        print("                 \,_/-"`  `-'\n")
    def pokemon6(self):# Wigglytuff
        print("                    .~~-.        _.\n")
        print("           .''..    (_~)  ) _.-'. ;\n")
        print("           '.'..'..-(_~ _-'*. .'.'\n")
        print("             ''.'.. _ ~~  _  ';'\n")
        print("              .''. (_)   (_)  '.\n")
        print("              ;      "..."     '.\n")
        print("          .''.'.   .''`-'''.    '.''.\n")
        print("          '.  '   ;         ;    ;  ;\n")
        print("            '.   ;           ;   ' ;\n")
        print("             '.  ;           ;    ;\n")
        print("              '.  ;         ;   .'\n")
        print("              .'...:..___..:..':.\n")
        print("           .''     ..'    '...   ~)\n")
        print("          (.....'''           ''''\n")
    def pokemon7(self):
        print("                             .'.\n")
        print("                    _______ .'.'.\n")
        print("                  .'       '.' '\n")
        print("             .   ;           ;\n")
        print("           .' '.;      ...    ;\n")
        print("         .' '.  '.   .'   '.   ;\n")
        print("          '.  '.. :  ;   * ;   ;\n")
        print("            '. '.'   '.   .'   ;''.\n")
        print("              '';      '''    ;'.  '.\n")
        print("                /            ;.  '.'\n")
        print("              .''./._______.'| '.'\n")
        print("              '..'         | |\n")
        print("                          |~~~|\n")
        print("                           ~~~\n")
    def pokemon8(self):# Slowpoke
        print("                   .----..        .'.\n")
        print("                _.-~  __   ~~~...'' .'\n")
        print("              .'    .~  '''...  ..''\n")
        print("             .'   ..''''''..  ''\n")
        print("             '...'          '..\n")
        print("            ..'              '.'..\n")
        print("         ..'  .'               ;  '.\n")
        print("       .'\   :   /~~\       /~~-.__|)\n")
        print("       './__:   ; '. |.''''''..  ;\n")
        print("           :    `..''()      ()'.'\n")
        print("           :    .'  __..------_  ;\n")
        print("            : .  .-~      .  . ~-:\n")
        print("          _.-'  ;        _____    ).\n")
        print("         /_     ; `-__-~H     H~-'  '.\n")
        print("        (  \  _.'.  (_____   _..';._.')\n")
        print("         '.'~~    ~--...__~~~_.-'   `~\n")
    def pokemon9(self): # Diglett
        print("                  .''''''.\n")
        print("                 ;        ;\n")
        print("                ;  HP  HP  ;\n")
        print("               ;   H   H    ;\n")
        print("               ;     ___    ;\n")
        print("               ;    (___)   ;\n")
        print("               ;            ;\n")
        print("               ;            ;\n")
        print("              h;            ;g\n")
        print("            jg ggh      hgj gggf\n")
        print("          og  h   hgfgfj   f  j gh\n")
        print("            gh h  h      hg  g\n")
    def pokemon10(self):# Electrode
        print("                     ..-----..\n")
        print("                  .'-____---~'.\n")
        print("                 :             :\n")
        print("                : __    .   ..' :\n")
        print("               :  ; ~-.'  .'  ;  :\n")
        print("               :  `...O  '..O/ _-:\n")
        print("               :._         _.-~  :\n")
        print("                : ----~~~~~_..' :\n")
        print("                 :   `---~~ .' :\n")
        print("                  '.  `-__.' .'\n")
        print("                    ''-----'' \n")
